spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: password
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-description: "init"
    baseline-version: 0

server:
  port: 8082