CREATE SEQUENCE IF NOT EXISTS category_seq
START WITH 101
INCREMENT BY 1
MINVALUE 101
MAXVALUE 100000
NO CYCLE;

CREATE TABLE IF NOT EXISTS category (
  id BIGINT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('category_seq'),
  name VARCHAR(255),
  description VARCHAR(255)
);

CREATE SEQUENCE IF NOT EXISTS product_seq
START WITH 101
INCREMENT BY 1
MINVALUE 101
MAXVALUE 100000
NO CYCLE;

CREATE TABLE IF NOT EXISTS product (
  id BIGINT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('product_seq'),
  name VARCHAR(255),
  description VARCHAR(255),
  available_quantity DOUBLE PRECISION NOT NULL,
  price NUMERIC(38,2),
  category_id BIGINT CONSTRAINT fk_category REFERENCES category(id)
);
